apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add the namespace to the resources
namespace: demo-multi-node-multi-gpu

resources:
  - model-pvc.yaml # PVC for model storage
  - download-model-to-pvc.yaml # Download model to PVC
